server:
  port: 10023
  servlet:
    context-path: /gpt

wx:
  mp:
    appId: wx8ab124a12e48b4a1
    secret: 30187c22f584369cfbb572c8c409bb8a
    token: duchina1023
    aesKey: uC1pjOIVVKsnNEtEc11Z3rCCZP1MrbLM91h0puQCyGz

openai:
  apiKey: sk-f74h42wycNnxwpdtA7BfCe77DcE9741391787690960
  apiHost: https://www.wushuangai.com/